openapi: 3.0.0
info:
  title: Widget Service
  version: 0.0.0
tags:
  - name: Widgets
paths:
  /widgets:
    get:
      operationId: Widgets_list
      description: List widgets
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Widget'
      tags:
        - Widgets
    post:
      operationId: Widgets_create
      description: Create a widget
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
      tags:
        - Widgets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Widget'
  /widgets/{id}:
    get:
      operationId: Widgets_read
      description: Read widgets
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Widget'
      tags:
        - Widgets
components:
  schemas:
    Widget:
      type: object
      required:
        - id
        - name
        - email
        - count
        - weight
        - color
        - active
        - dateOfBirth
        - createdAt
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
          format: email
        count:
          type: integer
        weight:
          type: number
        height:
          type: number
        color:
          type: string
          enum:
            - red
            - blue
            - green
        active:
          type: boolean
        dateOfBirth:
          type: string
          format: date
        createdAt:
          type: string
          format: date-time
