export const protectedKeywords: Record<string, string> = {
  abstract: 'abstractValue',
  arguments: 'argumentsValue',
  'async *': 'asyncStarValue',
  'await *': 'awaitStarValue',
  boolean: 'booleanValue',
  break: 'breakValue',
  byte: 'byteValue',
  case: 'caseValue',
  catch: 'catchValue',
  char: 'charValue',
  'class *': 'classStarValue',
  'const *': 'constStarValue',
  continue: 'continueValue',
  debugger: 'debuggerValue',
  default: 'defaultValue',
  delete: 'deleteValue',
  do: 'doValue',
  double: 'doubleValue',
  else: 'elseValue',
  'enum *': 'enumStarValue',
  eval: 'evalValue',
  export: 'exportValue',
  'export *': 'exportStarValue',
  'extends *': 'extendsStarValue',
  false: 'falseValue',
  final: 'finalValue',
  finally: 'finallyValue',
  float: 'floatValue',
  for: 'forValue',
  goto: 'gotoValue',
  if: 'ifValue',
  implements: 'implementsValue',
  function: 'functionValue',
  'import *': 'importStarValue',
  in: 'inValue',
  instanceof: 'instanceofValue',
  int: 'intValue',
  interface: 'interfaceValue',
  'let *': 'letStarValue',
  long: 'longValue',
  native: 'nativeValue',
  new: 'newValue',
  null: 'nullValue',
  package: 'packageValue',
  private: 'privateValue',
  protected: 'protectedValue',
  public: 'publicValue',
  return: 'returnValue',
  short: 'shortValue',
  static: 'staticValue',
  'super *': 'superStarValue',
  switch: 'switchValue',
  synchronized: 'synchronizedValue',
  this: 'thisValue',
  throw: 'throwValue',
  throws: 'throwsValue',
  transient: 'transientValue',
  true: 'trueValue',
  try: 'tryValue',
  typeof: 'typeofValue',
  'using *': 'usingStarValue',
  var: 'varValue',
  void: 'voidValue',
  volatile: 'volatileValue',
  while: 'whileValue',
  with: 'withValue',
  yield: 'yieldValue'
}
