/**
 * Detects whether a project's `bundle.js` is in sync with its current
 * `deno.json#imports`. Closes the gap left after the post-clone /
 * post-install auto-bundle (`clone-headless.ts`, `install-headless.ts`):
 * if an operator hand-edits `deno.json` outside the CLI — adding a
 * `jsr:` import, swapping a local generator path, etc. — `bundle.js`
 * is no longer canonical, and the next `skmtc generate` will silently
 * skip the new code or load a removed one.
 *
 * The check compares the **set of generator import keys** the project
 * currently declares against the set baked into `worker.ts` (which is
 * the source `deno bundle` reads from). `worker.ts` is regenerated by
 * `Project.createWorker()` from `toGeneratorIds()`, so its imports are
 * a faithful snapshot of what `deno.json` looked like at bundle time.
 *
 * Returns a structured outcome so the caller can decide whether to
 * refuse-with-recipe (strict mode) or warn-then-continue.
 */

import { existsSync } from '@std/fs/exists'
import { join } from '@std/path/join'
import { toProjectPath } from '@/lib/to-project-path.ts'
import { parseModuleName } from '@skmtc/core/parseModuleName'

export type BundleFreshness =
  | {
      kind: 'fresh'
      message: string
    }
  | {
      kind: 'missing-worker'
      /** Path the worker was expected at. */
      workerPath: string
      message: string
    }
  | {
      kind: 'stale'
      /** Generator IDs declared in `deno.json#imports` today. */
      currentIds: string[]
      /** Generator IDs the on-disk `worker.ts` was built against. */
      bundleIds: string[]
      /** IDs in `deno.json` that aren't in the bundle. */
      added: string[]
      /** IDs in the bundle that aren't in `deno.json`. */
      removed: string[]
      message: string
      hint: string
    }

const generatorIdImportPattern = /^import\s+\w+\s+from\s+['"]([^'"]+)['"]/gm

/**
 * Extracts the generator ids from a `worker.ts` source file by reading
 * each `import X from '...'` line. The CLI's worker template
 * (`to-worker.ts`) emits exactly one such line per generator id, so a
 * regex over the top of the file is sufficient — no parser needed.
 *
 * Filters out non-generator imports (specifically `@skmtc/worker`,
 * which `to-worker.ts` always emits) so the result is comparable to
 * `RootDenoJson.toGeneratorIds()`.
 */
const extractBundleGeneratorIds = (workerSource: string): string[] => {
  const ids: string[] = []
  for (const match of workerSource.matchAll(generatorIdImportPattern)) {
    const id = match[1]
    if (id === '@skmtc/worker') continue
    ids.push(id)
  }
  return ids
}

type Imports = Record<string, string>

const readProjectImports = (projectPath: string): Imports => {
  const denoJsonPath = join(projectPath, 'deno.json')
  if (!existsSync(denoJsonPath)) return {}
  try {
    const parsed = JSON.parse(Deno.readTextFileSync(denoJsonPath))
    const imports = parsed?.imports
    if (!imports || typeof imports !== 'object') return {}
    const out: Imports = {}
    for (const [key, value] of Object.entries(imports)) {
      if (typeof value === 'string') out[key] = value
    }
    return out
  } catch {
    return {}
  }
}

const toGeneratorIds = (imports: Imports): string[] =>
  Object.keys(imports).filter(id => parseModuleName(id).packageName.startsWith('gen-'))

export const checkBundleFreshness = ({
  projectName
}: {
  projectName: string
}): BundleFreshness => {
  const projectPath = toProjectPath(projectName)
  const imports = readProjectImports(projectPath)
  const currentIds = toGeneratorIds(imports)

  // Remote-only (all-`jsr:`) projects get the same treatment as
  // projects with cloned generators: `generate` loads the
  // project-local `bundle.js`, so a `worker.ts` snapshot must exist
  // and match `deno.json#imports` regardless of where the generator
  // source comes from.
  const workerPath = join(projectPath, 'worker.ts')
  if (!existsSync(workerPath)) {
    return {
      kind: 'missing-worker',
      workerPath,
      message:
        `Expected ${workerPath} to exist but it does not. Run \`skmtc bundle ${projectName}\` to build it.`
    }
  }

  const workerSource = Deno.readTextFileSync(workerPath)
  const bundleIds = extractBundleGeneratorIds(workerSource)

  const current = new Set(currentIds)
  const bundle = new Set(bundleIds)
  const added = currentIds.filter(id => !bundle.has(id))
  const removed = bundleIds.filter(id => !current.has(id))

  if (added.length === 0 && removed.length === 0) {
    return {
      kind: 'fresh',
      message: `bundle.js matches deno.json (${currentIds.length} generator(s)).`
    }
  }

  const addedHint =
    added.length > 0 ? `add: ${added.join(', ')}` : ''
  const removedHint =
    removed.length > 0 ? `remove: ${removed.join(', ')}` : ''
  return {
    kind: 'stale',
    currentIds,
    bundleIds,
    added,
    removed,
    message: `bundle.js is out of sync with deno.json — ${[addedHint, removedHint]
      .filter(Boolean)
      .join('; ')}`,
    hint: `Run \`skmtc bundle ${projectName}\` (or \`skmtc dev ${projectName}\`) to rebuild before generating.`
  }
}
