/**
 * Source collection for `deploy`. Walks the project root and returns the
 * user-authored source files. `deploy-headless` then posts these (one
 * multipart `files` part each) alongside the compiled `bundle` part in the
 * single atomic `POST /v1/stacks/{account}/{stack}/deployments` request; the
 * hub writes the tree to R2, reconciles the stack's `stack_generator_refs`
 * from the uploaded `deno.json` (gen-*-prefixed local paths → `cloned`,
 * gen-*-prefixed JSR imports → `imported`), and populates the deployment's
 * source columns.
 *
 * The walker mirrors the conventions in
 * `skmtc-hub/spike/live-test/setup-fixtures.ts#collectProjectFiles`:
 *   - skip entries whose name starts with `.`, EXCEPT `.settings`
 *     (that's where client.json lives)
 *   - skip derived files at the project root: the `server.ts` / `server.js`
 *     bundle artefacts, plus legacy `bundle.js` / `worker.ts`. These are
 *     either uploaded separately (the bundle) or regenerated by the engine —
 *     the source upload is for user-authored code only.
 */

import { join } from 'jsr:@std/path@^1'

export type SourceFile = {
  /** Path relative to the project root, forward-slashed. */
  path: string
  /** Raw bytes. Non-shared `ArrayBuffer` so `fetch` accepts the body. */
  bytes: ArrayBuffer
  /** Best-guess MIME type — informational for the hub. */
  contentType: string
}

/**
 * Read a file into a fresh `ArrayBuffer`. `Deno.readFile` returns
 * `Uint8Array<ArrayBufferLike>` whose underlying buffer might be a
 * `SharedArrayBuffer`, which fetch / Blob bodies reject. Copy into a
 * non-shared `ArrayBuffer`.
 */
const readArrayBuffer = async (path: string): Promise<ArrayBuffer> => {
  const u8 = await Deno.readFile(path)
  const buf = new ArrayBuffer(u8.byteLength)
  new Uint8Array(buf).set(u8)
  return buf
}

/**
 * Files at the project root that `bundleDeploy` and the engine produce.
 * These are either uploaded separately (the bundle) or regenerated at
 * deploy time, so they don't belong in the source upload.
 */
const DERIVED_ROOT_FILES = new Set(['server.ts', 'server.js', 'bundle.js', 'worker.ts'])

/**
 * File extensions that are binary assets — images, video, fonts,
 * archives. These bloat the upload past the hub's per-file limit
 * (1 MB) without contributing to anything the source view can render.
 * Stock generators sometimes ship demo MP4s / illustrations under
 * `assets/` that fall in this category.
 */
const BINARY_ASSET_EXTENSIONS = new Set([
  'mp4', 'webm', 'mov', 'mkv',
  'png', 'jpg', 'jpeg', 'gif', 'webp', 'bmp', 'ico',
  'woff', 'woff2', 'ttf', 'otf', 'eot',
  'zip', 'tar', 'gz', 'tgz', 'bz2', '7z',
  'pdf'
])

const guessContentType = (path: string): string => {
  const ext = path.slice(path.lastIndexOf('.') + 1).toLowerCase()
  switch (ext) {
    case 'ts':
    case 'tsx':
    case 'js':
    case 'jsx':
      return 'text/typescript; charset=utf-8'
    case 'json':
    case 'jsonc':
      return 'application/json; charset=utf-8'
    case 'md':
    case 'markdown':
      return 'text/markdown; charset=utf-8'
    default:
      return 'text/plain; charset=utf-8'
  }
}

/**
 * Walk `projectRoot` and collect every source file. Returns the list
 * sorted by path. Skips dotfiles (except `.settings`) and derived
 * files (`bundle.js`, `worker.ts` at the root).
 */
export const collectSourceFiles = async (projectRoot: string): Promise<SourceFile[]> => {
  const out: SourceFile[] = []

  const walk = async (dir: string, prefix: string): Promise<void> => {
    for await (const entry of Deno.readDir(dir)) {
      const isHidden = entry.name.startsWith('.')
      // At the project root, .settings/ is allowed; everywhere else,
      // dotfiles are skipped.
      if (isHidden && !(prefix === '' && entry.name === '.settings')) continue
      if (prefix === '' && entry.isFile && DERIVED_ROOT_FILES.has(entry.name)) continue

      const rel = prefix ? `${prefix}/${entry.name}` : entry.name
      const abs = join(dir, entry.name)

      if (entry.isDirectory) {
        await walk(abs, rel)
      } else if (entry.isFile) {
        const ext = entry.name.slice(entry.name.lastIndexOf('.') + 1).toLowerCase()
        if (BINARY_ASSET_EXTENSIONS.has(ext)) continue
        const bytes = await readArrayBuffer(abs)
        out.push({ path: rel, bytes, contentType: guessContentType(rel) })
      }
    }
  }

  await walk(projectRoot, '')
  out.sort((a, b) => a.path.localeCompare(b.path))
  return out
}
