/**
 * Source collection for `publish`. Walks the project root and returns the
 * user-authored source files. `publish-headless` then posts these (one
 * multipart `files` part each) alongside the `version` and compiled `bundle`
 * parts in the single atomic `POST /v1/stacks/{account}/{stack}/versions`
 * request; the hub writes the tree to R2, reconciles the stack's
 * `stack_generator_refs` from the uploaded `deno.json` (gen-*-prefixed local
 * paths → `cloned`, gen-*-prefixed JSR imports → `imported`), and populates
 * the stack version's source columns.
 *
 * What's uploaded is decided by a gitignore-style filter rather than a fixed
 * allow-list — the default is "upload everything the user authored" so we don't
 * silently drop files a stack legitimately needs. A set of built-in defaults
 * skips the things that are never source (derived bundle/engine artefacts, VCS,
 * deps, OS cruft, secrets, binary assets), and a project's optional
 * `.skmtcignore` (gitignore syntax) lets a stack add its own exclusions or
 * re-include something a default excludes (`!foo`).
 */

import { join } from 'jsr:@std/path@^1'
import ignore from 'ignore'

export type SourceFile = {
  /** Path relative to the project root, forward-slashed. */
  path: string
  /** Raw bytes. Non-shared `ArrayBuffer` so `fetch` accepts the body. */
  bytes: ArrayBuffer
  /** Best-guess MIME type — informational for the hub. */
  contentType: string
}

/**
 * Built-in ignore patterns (gitignore syntax), always applied before a
 * project's `.skmtcignore`. These cover what is never user-authored source:
 *
 *  - derived deploy/engine artefacts at the project root — the `server.ts` /
 *    `server.js` bundle entry, plus `bundle.js` / `worker.ts`. Uploaded
 *    separately (the bundle) or regenerated by the engine. Root-anchored so a
 *    generator that legitimately ships a nested `worker.ts` isn't caught.
 *  - VCS, dependencies, OS cruft, and secrets (`.env*`).
 *  - binary assets (images / video / fonts / archives) — they blow past the
 *    hub's per-file limit and the source view can't render them.
 *
 * NB: unlike the old hand-rolled filter, dotfiles are NOT skipped wholesale —
 * a stack may legitimately want to ship one. Known-unwanted dotfiles are
 * listed explicitly; anything else uploads.
 */
const DEFAULT_IGNORE = [
  '/server.ts',
  '/server.js',
  '/bundle.js',
  '/worker.ts',
  '.git/',
  'node_modules/',
  '.DS_Store',
  '.env',
  '.env.*',
  '*.mp4',
  '*.webm',
  '*.mov',
  '*.mkv',
  '*.png',
  '*.jpg',
  '*.jpeg',
  '*.gif',
  '*.webp',
  '*.bmp',
  '*.ico',
  '*.woff',
  '*.woff2',
  '*.ttf',
  '*.otf',
  '*.eot',
  '*.zip',
  '*.tar',
  '*.gz',
  '*.tgz',
  '*.bz2',
  '*.7z',
  '*.pdf'
]

/** Project-root ignore file (gitignore syntax), layered over the defaults. */
export const SKMTC_IGNORE_FILE = '.skmtcignore'

/**
 * Seed `.skmtcignore` written into new projects by `init`. The built-in
 * defaults above already cover derived bundles, deps, secrets and binaries, so
 * the seed is mostly a documented starting point — plus the publish/generate
 * logs, which live under `.settings` (kept for `client.json`) and are pure
 * noise in an upload.
 */
export const SKMTCIGNORE_TEMPLATE = `# .skmtcignore — files to exclude from \`skmtc publish\` uploads (gitignore syntax).
#
# Built-in defaults already skip derived bundles (server.ts/js, bundle.js,
# worker.ts), node_modules, .git, secrets (.env*), and binary assets.
# Add project-specific exclusions below; use \`!pattern\` to re-include something
# a default excludes.

# publish / generate logs
.settings/logs.txt
.settings/error-logs.txt
`

/**
 * Read a file into a fresh `ArrayBuffer`. `Deno.readFile` returns
 * `Uint8Array<ArrayBufferLike>` whose underlying buffer might be a
 * `SharedArrayBuffer`, which fetch / Blob bodies reject. Copy into a
 * non-shared `ArrayBuffer`.
 */
const readArrayBuffer = async (path: string): Promise<ArrayBuffer> => {
  const u8 = await Deno.readFile(path)
  const buf = new ArrayBuffer(u8.byteLength)
  new Uint8Array(buf).set(u8)
  return buf
}

const guessContentType = (path: string): string => {
  const ext = path.slice(path.lastIndexOf('.') + 1).toLowerCase()
  switch (ext) {
    case 'ts':
    case 'tsx':
    case 'js':
    case 'jsx':
      return 'text/typescript; charset=utf-8'
    case 'json':
    case 'jsonc':
      return 'application/json; charset=utf-8'
    case 'md':
    case 'markdown':
      return 'text/markdown; charset=utf-8'
    default:
      return 'text/plain; charset=utf-8'
  }
}

/**
 * Build the upload filter: built-in defaults layered with the project's
 * optional `.skmtcignore`. A missing ignore file is fine; any other read error
 * propagates (a corrupt/permission-denied ignore file shouldn't silently widen
 * the upload).
 */
const toUploadFilter = async (projectRoot: string) => {
  const matcher = ignore().add(DEFAULT_IGNORE)
  try {
    matcher.add(await Deno.readTextFile(join(projectRoot, SKMTC_IGNORE_FILE)))
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error
  }
  return matcher
}

/**
 * Walk `projectRoot` and collect every source file the upload filter keeps.
 * Returns the list sorted by path. Ignored directories are pruned (not
 * descended into); ignored files are skipped.
 */
export const collectSourceFiles = async (projectRoot: string): Promise<SourceFile[]> => {
  const matcher = await toUploadFilter(projectRoot)
  const out: SourceFile[] = []

  const walk = async (dir: string, prefix: string): Promise<void> => {
    for await (const entry of Deno.readDir(dir)) {
      const rel = prefix ? `${prefix}/${entry.name}` : entry.name
      const abs = join(dir, entry.name)

      if (entry.isDirectory) {
        // gitignore directory patterns (`node_modules/`, `.git/`) match a
        // trailing-slash path; prune so we don't descend into ignored trees.
        if (matcher.ignores(`${rel}/`)) continue
        await walk(abs, rel)
      } else if (entry.isFile) {
        if (matcher.ignores(rel)) continue
        const bytes = await readArrayBuffer(abs)
        out.push({ path: rel, bytes, contentType: guessContentType(rel) })
      }
    }
  }

  await walk(projectRoot, '')
  out.sort((a, b) => a.path.localeCompare(b.path))
  return out
}

/**
 * Collect a project's BASE FILES — the hand-authored app tree the preview
 * container needs to compile + render generated code — for `skmtc push
 * --base-files`. Walks `appRoot` with the same gitignore-style methodology as
 * {@link collectSourceFiles} (built-in defaults + the app root's
 * `.skmtcignore`), additionally excluding `.skmtc/` (the stack workspace,
 * published separately as a version) and `generatedPaths` (manifest-recorded
 * output, regenerated in the preview). Returns `{ path: textContent }` keyed by
 * app-root-relative path — the shape the `/preview/base-files` upload expects.
 */
export const collectBaseFiles = async (
  appRoot: string,
  generatedPaths: ReadonlySet<string>
): Promise<Record<string, string>> => {
  const matcher = ignore().add(DEFAULT_IGNORE).add('.skmtc/')
  try {
    matcher.add(await Deno.readTextFile(join(appRoot, SKMTC_IGNORE_FILE)))
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error
  }

  const out: Record<string, string> = {}
  const walk = async (dir: string, prefix: string): Promise<void> => {
    for await (const entry of Deno.readDir(dir)) {
      const rel = prefix ? `${prefix}/${entry.name}` : entry.name
      const abs = join(dir, entry.name)
      if (entry.isDirectory) {
        if (matcher.ignores(`${rel}/`)) continue
        await walk(abs, rel)
      } else if (entry.isFile) {
        if (matcher.ignores(rel) || generatedPaths.has(rel)) continue
        out[rel] = await Deno.readTextFile(abs)
      }
    }
  }
  await walk(appRoot, '')
  return out
}
