/**
 * Source upload for `deploy`. Walks the project root, builds a
 * multipart body with one part per file, and POSTs to the hub's
 * `POST /v1/stacks/{account}/{stack}/releases/{version}/source`.
 *
 * The hub:
 *   - writes every file to R2 at `source/{stackId}/{version}/<path>`
 *   - parses the uploaded `deno.json` and reconciles
 *     `stack_generator_refs` (gen-*-prefixed local paths → `cloned`,
 *     gen-*-prefixed JSR imports → `imported`)
 *   - populates the release row's source_root_key / source_file_count /
 *     source_total_bytes / source_uploaded_at
 *
 * The walker mirrors the conventions in
 * `skmtc-hub/spike/live-test/setup-fixtures.ts#collectClonedFiles`:
 *   - skip entries whose name starts with `.`, EXCEPT `.settings`
 *     (that's where client.json lives)
 *   - skip derived files at the project root: the `server.ts` /
 *     `server.js` / `runtime/` artefacts produced by `bundleSplit`,
 *     plus legacy `bundle.js` / `worker.ts`. These are either uploaded
 *     separately (the bundle) or regenerated by the engine — the
 *     source upload is for user-authored code only.
 */

import { join } from 'jsr:@std/path@^1'

export type SourceFile = {
  /** Path relative to the project root, forward-slashed. */
  path: string
  /** Raw bytes. Non-shared `ArrayBuffer` so `fetch` accepts the body. */
  bytes: ArrayBuffer
  /** Best-guess MIME type — informational for the hub. */
  contentType: string
}

/**
 * Read a file into a fresh `ArrayBuffer`. `Deno.readFile` returns
 * `Uint8Array<ArrayBufferLike>` whose underlying buffer might be a
 * `SharedArrayBuffer`, which fetch / Blob bodies reject. Copy into a
 * non-shared `ArrayBuffer`.
 */
const readArrayBuffer = async (path: string): Promise<ArrayBuffer> => {
  const u8 = await Deno.readFile(path)
  const buf = new ArrayBuffer(u8.byteLength)
  new Uint8Array(buf).set(u8)
  return buf
}

/**
 * Files at the project root that `bundleSplit` and the engine produce.
 * These are either uploaded separately (the bundle) or regenerated at
 * deploy time, so they don't belong in the source upload.
 */
const DERIVED_ROOT_FILES = new Set(['server.ts', 'server.js', 'bundle.js', 'worker.ts'])

/** Directories at the project root that hold derived output. */
const DERIVED_ROOT_DIRS = new Set(['runtime'])

/**
 * File extensions that are binary assets — images, video, fonts,
 * archives. These bloat the upload past the hub's per-file limit
 * (1 MB) without contributing to anything the source view can render.
 * Stock generators sometimes ship demo MP4s / illustrations under
 * `assets/` that fall in this category.
 */
const BINARY_ASSET_EXTENSIONS = new Set([
  'mp4', 'webm', 'mov', 'mkv',
  'png', 'jpg', 'jpeg', 'gif', 'webp', 'bmp', 'ico',
  'woff', 'woff2', 'ttf', 'otf', 'eot',
  'zip', 'tar', 'gz', 'tgz', 'bz2', '7z',
  'pdf'
])

const guessContentType = (path: string): string => {
  const ext = path.slice(path.lastIndexOf('.') + 1).toLowerCase()
  switch (ext) {
    case 'ts':
    case 'tsx':
    case 'js':
    case 'jsx':
      return 'text/typescript; charset=utf-8'
    case 'json':
    case 'jsonc':
      return 'application/json; charset=utf-8'
    case 'md':
    case 'markdown':
      return 'text/markdown; charset=utf-8'
    default:
      return 'text/plain; charset=utf-8'
  }
}

/**
 * Walk `projectRoot` and collect every source file. Returns the list
 * sorted by path. Skips dotfiles (except `.settings`) and derived
 * files (`bundle.js`, `worker.ts` at the root).
 */
export const collectSourceFiles = async (projectRoot: string): Promise<SourceFile[]> => {
  const out: SourceFile[] = []

  const walk = async (dir: string, prefix: string): Promise<void> => {
    for await (const entry of Deno.readDir(dir)) {
      const isHidden = entry.name.startsWith('.')
      // At the project root, .settings/ is allowed; everywhere else,
      // dotfiles are skipped.
      if (isHidden && !(prefix === '' && entry.name === '.settings')) continue
      if (prefix === '' && entry.isFile && DERIVED_ROOT_FILES.has(entry.name)) continue
      if (prefix === '' && entry.isDirectory && DERIVED_ROOT_DIRS.has(entry.name)) continue

      const rel = prefix ? `${prefix}/${entry.name}` : entry.name
      const abs = join(dir, entry.name)

      if (entry.isDirectory) {
        await walk(abs, rel)
      } else if (entry.isFile) {
        const ext = entry.name.slice(entry.name.lastIndexOf('.') + 1).toLowerCase()
        if (BINARY_ASSET_EXTENSIONS.has(ext)) continue
        const bytes = await readArrayBuffer(abs)
        out.push({ path: rel, bytes, contentType: guessContentType(rel) })
      }
    }
  }

  await walk(projectRoot, '')
  out.sort((a, b) => a.path.localeCompare(b.path))
  return out
}

/**
 * POST the collected source tree to the hub. Returns the number of
 * files uploaded and the total byte size.
 */
export const uploadSource = async ({
  hubUrl,
  token,
  account,
  slug,
  version,
  files
}: {
  hubUrl: string
  token: string
  account: string
  slug: string
  version: string
  files: SourceFile[]
}): Promise<{ fileCount: number; totalBytes: number }> => {
  if (files.length === 0) throw new Error('no source files to upload')

  const form = new FormData()
  let totalBytes = 0
  for (const file of files) {
    // The hub reads the part's filename as the file's path relative to
    // the project root. FormData sets the part's
    // `Content-Disposition: filename` from the third argument.
    form.append('files', new Blob([file.bytes], { type: file.contentType }), file.path)
    totalBytes += file.bytes.byteLength
  }

  const response = await fetch(
    `${hubUrl}/v1/stacks/${account}/${slug}/releases/${version}/source`,
    {
      method: 'POST',
      headers: { authorization: `Bearer ${token}` },
      body: form
    }
  )

  if (!response.ok) {
    const text = await response.text()
    throw new Error(`source upload failed (${response.status}): ${text.slice(0, 500)}`)
  }

  // Drain the response so the connection can be reused.
  await response.text()

  return { fileCount: files.length, totalBytes }
}
