import type { Definition } from '../dsl/Definition.ts'
import type { Stringable } from '../dsl/Stringable.ts'
import type { GeneratorKey } from './GeneratorKeys.ts'

/**
 * 'force' - will generate content even it is not selected.
 * Use this option when generating code via a dependency.
 * For example, when you are generating a form and it needs
 * an accompanying API client as well. You should use 'force'
 * when generating the API client to ensure it is generated
 * event the API client itself is not selected.
 *
 * 'regular' - will generate content only if it is selected.
 */

export type GenerationType = 'force' | 'regular'

/**
 * Represents a value that can be generated by the SKMTC pipeline.
 * 
 * Combines the Stringable interface with optional generator key metadata,
 * allowing generated content to be associated with specific generators for
 * tracking and organization purposes.
 */
export type GeneratedValue = Stringable & {
  generatorKey?: GeneratorKey
}

/**
 * Conditional type for generated definitions based on generation type.
 * 
 * When generation type is 'force', always returns a Definition.
 * When generation type is 'regular', returns Definition or undefined
 * based on whether the content is selected for generation.
 * 
 * @template V - The generated value type extending GeneratedValue
 * @template T - The generation type ('force' or 'regular')
 */
export type GeneratedDefinition<
  V extends GeneratedValue,
  T extends GenerationType
> = T extends 'force' ? Definition<V> : Definition<V> | undefined
