import { assertEquals } from '@std/assert'
import type { GenerateContextType } from '@skmtc/core/generate'
import { CsAttribute } from './CsAttribute.ts'
import { CsDefinition } from './CsDefinition.ts'
import { CsFile } from './CsFile.ts'
import { CsImport } from './CsImport.ts'
import { CsPropertyList } from './CsPropertyList.ts'
import { createRecord } from './createIdentifier.ts'

// Construction only stores `context`; `toString()` never reads it (test-only cast).
const context = {} as unknown as GenerateContextType

Deno.test('namespace directive is derived from the file path', () => {
  const file = new CsFile({ path: '@/Acme/Api/Models/User.generated.cs', settings: undefined })

  assertEquals(file.namespaceName, 'Acme.Api.Models')
})

Deno.test('a root-level file renders the header pair and no namespace line', () => {
  const file = new CsFile({ path: '@/Scratch.generated.cs', settings: undefined })
  file.definitions.set(
    'Marker',
    new CsDefinition({
      context,
      identifier: createRecord('Marker'),
      value: new CsPropertyList([])
    })
  )

  assertEquals(
    file.toString(),
    '// <auto-generated/>\n#nullable enable\n\npublic sealed partial record Marker;\n'
  )
})

Deno.test('usings render sorted and deduplicated across modules resolving to one namespace', () => {
  const file = new CsFile({ path: '@/Acme/Api/Models/Order.generated.cs', settings: undefined })
  file.addImports([
    CsImport.fromConcise('System.Text.Json.Serialization', ['JsonPropertyName']),
    CsImport.fromConcise('System.Text.Json', ['JsonElement']),
    // Two peer files in one directory → identical using lines → one rendered
    CsImport.fromConcise('@/Acme/Shared/Money.generated.cs', ['Money']),
    CsImport.fromConcise('@/Acme/Shared/Currency.generated.cs', ['Currency'])
  ])
  file.definitions.set(
    'Order',
    new CsDefinition({
      context,
      identifier: createRecord('Order'),
      value: new CsPropertyList([])
    })
  )

  assertEquals(
    file.toString(),
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using Acme.Shared;\n' +
      'using System.Text.Json;\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Order;\n'
  )
})

Deno.test('same-namespace usings are suppressed (C# needs no using for them)', () => {
  const file = new CsFile({ path: '@/Acme/Api/Models/Order.generated.cs', settings: undefined })
  file.addImports([
    // The Driver's cross-file peer import: same namespace → suppressed
    CsImport.fromConcise('@/Acme/Api/Models/User.generated.cs', ['User']),
    // Different namespace → renders
    CsImport.fromConcise('@/Acme/Shared/Money.generated.cs', ['Money'])
  ])
  file.definitions.set(
    'Order',
    new CsDefinition({
      context,
      identifier: createRecord('Order'),
      value: new CsPropertyList([])
    })
  )

  assertEquals(
    file.toString(),
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using Acme.Shared;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      'public sealed partial record Order;\n'
  )
})

Deno.test('the Track 2 User-DTO worked example renders byte-for-byte (CS-A spec snapshot)', () => {
  class DocumentedPropertiesValue {
    description = 'A user of the system. Escaped: &, <, >'
    properties: CsPropertyList

    constructor(properties: CsPropertyList) {
      this.properties = properties
    }

    toString(): string {
      return `${this.properties}`
    }
  }

  const file = new CsFile({ path: '@/Acme/Api/Models/User.generated.cs', settings: undefined })

  file.addImports([
    CsImport.fromConcise('System.Collections.Generic', ['IDictionary']),
    CsImport.fromConcise('System.Text.Json', ['JsonElement']),
    CsImport.fromConcise('System.Text.Json.Serialization', [
      'JsonPropertyName',
      'JsonIgnore',
      'JsonExtensionData'
    ])
  ])

  file.definitions.set(
    'User',
    new CsDefinition({
      context,
      identifier: createRecord('User'),
      value: new DocumentedPropertiesValue(
        new CsPropertyList([
          {
            name: 'UserId',
            type: 'string',
            required: true,
            attributes: [new CsAttribute('JsonPropertyName', ['"user_id"'])]
          },
          {
            name: 'Name',
            type: 'string',
            nullable: true,
            attributes: [
              new CsAttribute('JsonPropertyName', ['"name"']),
              new CsAttribute('JsonIgnore', ['Condition = JsonIgnoreCondition.WhenWritingNull'])
            ]
          },
          {
            name: 'Note',
            type: 'string',
            nullable: true,
            required: true,
            attributes: [new CsAttribute('JsonPropertyName', ['"note"'])]
          },
          {
            name: 'AdditionalProperties',
            type: 'IDictionary<string, JsonElement>',
            nullable: true,
            attributes: [new CsAttribute('JsonExtensionData')]
          }
        ])
      )
    })
  )

  assertEquals(
    file.toString(),
    '// <auto-generated/>\n' +
      '#nullable enable\n' +
      '\n' +
      'using System.Collections.Generic;\n' +
      'using System.Text.Json;\n' +
      'using System.Text.Json.Serialization;\n' +
      '\n' +
      'namespace Acme.Api.Models;\n' +
      '\n' +
      '/// <summary>\n' +
      '/// A user of the system. Escaped: &amp;, &lt;, &gt;\n' +
      '/// </summary>\n' +
      'public sealed partial record User\n' +
      '{\n' +
      '    [JsonPropertyName("user_id")]\n' +
      '    public required string UserId { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("name")]\n' +
      '    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]\n' +
      '    public string? Name { get; init; }\n' +
      '\n' +
      '    [JsonPropertyName("note")]\n' +
      '    public required string? Note { get; init; }\n' +
      '\n' +
      '    [JsonExtensionData]\n' +
      '    public IDictionary<string, JsonElement>? AdditionalProperties { get; init; }\n' +
      '}\n'
  )
})
