import { CodeFileBase } from '@skmtc/core'
import type { ClientSettings } from '@skmtc/core'
import { CsImport } from './CsImport.ts'
import { toNamespaceName } from './toNamespaceName.ts'

/**
 * Constructor arguments for {@link CsFile} — the `Lang.createFile` shape.
 */
export type CsFileArgs = {
  path: string
  settings: ClientSettings | undefined
}

/**
 * C#'s concrete code file. Inherits the neutral import collection +
 * merge from {@link CodeFileBase} and adds the C#-specific pieces:
 *
 * - the `// <auto-generated/>` + `#nullable enable` header pair (D9).
 *   The pair is compiler-mandated, not stylistic: the auto-generated
 *   marker suppresses consumer analyzers AND removes the file from the
 *   project's nullable context — a generated file using `?` without the
 *   explicit directive fails to compile with CS8669 (scratch-proof 2).
 * - the file-scoped `namespace X.Y;` directive (C# 10), DERIVED from the
 *   file's own path via {@link toNamespaceName} — the export path
 *   encodes the namespace (`@/Acme/Api/Models/User.generated.cs` →
 *   `namespace Acme.Api.Models;`); `client.json#settings.basePath`
 *   points at the consumer's project source root (D7).
 * - **same-namespace using suppression**: any import whose resolved
 *   namespace equals this file's namespace is omitted at render
 *   (same-namespace symbols need no `using` in C#). In particular the
 *   Driver's cross-file peer imports vanish when peers share the
 *   namespace (the common single-`baseNamespace` case).
 * - the rendering arrangement: header pair, usings (namespace-collapsed,
 *   deduplicated across modules, **sorted alphabetically** — not style,
 *   which is the consumer's formatter's job, but registration-order
 *   independence: the rendered bytes are what snapshot tests and
 *   byte-identical regression gates compare), the namespace directive,
 *   then definitions joined by blank lines. All usings are explicit —
 *   no reliance on the consumer's `ImplicitUsings` (D8).
 *
 * `reExports` cannot arrive by construction — C#'s concise register
 * vocabulary has no `reExports` field (C# has no re-export construct)
 * and the Driver never registers them — so rendering ignores the
 * (always empty) neutral map.
 */
export class CsFile extends CodeFileBase {
  /** The namespace this file declares — derived from `path`; `''` is the global namespace (no directive rendered). */
  namespaceName: string
  /** Held for the multi-package (`settings.packages`) story; unused in v1. */
  settings: ClientSettings | undefined

  constructor({ path, settings }: CsFileArgs) {
    super({ path })
    this.namespaceName = toNamespaceName(path)
    this.settings = settings
  }

  override toString(): string {
    const usingLines = Array.from(this.imports.values()).flatMap(importEntry => {
      if (!(importEntry instanceof CsImport)) {
        return [importEntry.toString()]
      }

      if (importEntry.resolvedNamespace() === this.namespaceName) {
        return []
      }

      return importEntry.toLines()
    })

    // Two modules can resolve to the same namespace (two peer files in
    // one directory) — the namespace-collapsed lines deduplicate here.
    // The comparison strips the trailing `;` so a namespace sorts before
    // its descendants (`using System.Text.Json;` before
    // `using System.Text.Json.Serialization;` — ordinally `;` > `.`
    // would reverse them).
    const sortedUsings = Array.from(new Set(usingLines)).sort((left, right) => {
      const leftKey = left.replace(/;$/, '')
      const rightKey = right.replace(/;$/, '')

      return leftKey < rightKey ? -1 : leftKey > rightKey ? 1 : 0
    })

    const definitions = Array.from(this.definitions.values())
      .map(definition => definition.toString())
      .join('\n\n')

    const sections = [
      '// <auto-generated/>\n#nullable enable',
      sortedUsings.join('\n'),
      this.namespaceName ? `namespace ${this.namespaceName};` : '',
      definitions
    ]

    return `${sections.filter(section => Boolean(section.length)).join('\n\n')}\n`
  }
}
