import WordRotate from '@/components/ui/word-rotate'
import MDX from '@/components/content/hero.mdx'

const Hero2 = () => {
  return (
    <div className="overflow-hidden py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 sm:gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-5">
          <div className="lg:col-span-3">
            <MDX />
          </div>

          <div className="lg:col-span-2">
            <h2 className="text-base font-semibold leading-7 text-indigo-600">Define outputs</h2>
            <h1 className="mt-2 text-3xl font-normal tracking-tight text-gray-900 sm:text-4xl">
              <div className="flex">
                Generate&nbsp;
                <WordRotate
                  className="break-after-right"
                  duration={10000}
                  words={['client code', 'Zod types', 'Forms', 'TypeScript']}
                />
              </div>
              <div>from API schema</div>
            </h1>
            <p className="mt-6 text-lg leading-8 text-gray-600">
              CodeSquared transformers use simple string templates to define output code.
            </p>
            <p className="mt-6 text-lg leading-8 text-gray-600">
              Using native behaviour makes code generation accessible to all JavaScript developers.
              This approach also enables us to reuse and nest code generated by other transformers.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Hero2
