name: PR

on:
  pull_request:
    types: ['opened', 'synchronize']

env:
  CI: true

jobs:
  test-pr:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install
        run: yarn

      - name: Lint
        run: |
          yarn  lint

      - name: TypeCheck
        run: |
          yarn check

      - name: Test
        run: |
          yarn test:ci

      - name: Build
        run: |
          yarn  build
