import type { DefinitionBase } from '@/dsl/Definition.ts'
import type { Stringable } from '@/dsl/Stringable.ts'
import type { GeneratorKey } from '@/dsl/GeneratorKeys.ts'

/**
 * Represents a value that can be generated by the SKMTC pipeline.
 *
 * Combines the Stringable interface with optional generator key metadata,
 * allowing generated content to be associated with specific generators for
 * tracking and organization purposes.
 */
export type GeneratedValue = Stringable & {
  generatorKey?: GeneratorKey
}

/**
 * Type for generated definitions.
 *
 * @template V - The generated value type extending GeneratedValue
 */
export type GeneratedDefinition<V extends GeneratedValue> = DefinitionBase<V>
